In [1]:
import numpy as np

In [3]:
a = np.random.randn((10))

In [4]:
b = np.random.randn((10))

In [5]:
a

array([ 0.30184538, -0.03582968,  0.88672986, -1.61752763, -0.21737069,
        0.86392725,  0.17459069, -0.17244382,  0.92210195, -0.66069185])

In [6]:
b

array([-0.77859143,  1.09926181, -1.01149441,  0.20733063, -1.1314795 ,
        1.03392557, -2.25644302,  0.89480478,  0.31969385, -1.07476649])

In [7]:
a+b

array([-0.47674606,  1.06343213, -0.12476455, -1.41019699, -1.34885019,
        1.89785282, -2.08185233,  0.72236095,  1.2417958 , -1.73545833])

In [8]:
a-b

array([ 1.08043681, -1.13509149,  1.89822427, -1.82485826,  0.9141088 ,
       -0.16999832,  2.43103371, -1.0672486 ,  0.6024081 ,  0.41407464])

In [9]:
a*b

array([-0.23501422, -0.0393862 , -0.8969223 , -0.33536303,  0.24595048,
        0.89323648, -0.39395394, -0.15430356,  0.29479032,  0.71008945])

In [10]:
1/a

array([  3.3129545 , -27.90982395,   1.12773917,  -0.61822746,
        -4.6004362 ,   1.15750487,   5.72768226,  -5.79898991,
         1.08447878,  -1.51356492])

In [11]:
a>0

array([ True, False,  True, False, False,  True,  True, False,  True,
       False])

In [12]:
a[a>0]

array([0.30184538, 0.88672986, 0.86392725, 0.17459069, 0.92210195])