In [2]:
import numpy as np

In [3]:
x = np.array([1,2,3,4,5,6,7,8,9])

In [4]:
x[4]
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
x>5

array([False, False, False, False, False,  True,  True,  True,  True])

# Bolean Indexing

In [6]:
x[x>5]

array([6, 7, 8, 9])

# Fancy Slicing

In [7]:
x[[3,2]]

array([4, 3])

# Slicing 

In [11]:
Ar = np.random.randn(10,10)

In [12]:
Ar

array([[-0.5421967 ,  0.20519908,  0.25703849, -0.10050931, -1.21237108,
        -1.61526741, -1.2717805 ,  0.06918799,  1.68844382,  2.02060615],
       [ 1.41186957,  0.94025984, -0.75769337,  2.36576275,  0.05619088,
        -1.34728479,  1.49453025,  0.65605025,  0.24515344, -0.90122991],
       [ 0.70728982, -0.40604579, -1.45119135,  1.56556291, -1.54351312,
        -1.35787272, -1.30009374, -1.70982567, -1.49051037, -1.11631523],
       [-0.60360182, -0.54863663,  0.59601694, -0.74212364,  0.82650736,
        -0.2314955 , -0.52914697, -1.60536731, -1.80998878,  1.041505  ],
       [-0.45211338,  1.09802136,  1.44453281,  0.66108747, -0.17155868,
         0.57834297,  1.67422269, -2.36804827, -0.48205902,  1.0188351 ],
       [-1.58082051, -0.40375897, -1.78336633, -0.84720089,  0.39857613,
        -0.36448714,  0.84079761,  0.08613214,  1.80862438,  0.4926349 ],
       [-1.01287266, -0.33034777, -0.40344416,  0.68774648,  0.45777982,
        -1.36892375,  0.10126275, -0.91269381

In [13]:
Ar[0]

array([-0.5421967 ,  0.20519908,  0.25703849, -0.10050931, -1.21237108,
       -1.61526741, -1.2717805 ,  0.06918799,  1.68844382,  2.02060615])

In [14]:
Ar[0][5]

-1.6152674132067928

In [15]:
Ar[1:10:2]

array([[ 1.41186957,  0.94025984, -0.75769337,  2.36576275,  0.05619088,
        -1.34728479,  1.49453025,  0.65605025,  0.24515344, -0.90122991],
       [-0.60360182, -0.54863663,  0.59601694, -0.74212364,  0.82650736,
        -0.2314955 , -0.52914697, -1.60536731, -1.80998878,  1.041505  ],
       [-1.58082051, -0.40375897, -1.78336633, -0.84720089,  0.39857613,
        -0.36448714,  0.84079761,  0.08613214,  1.80862438,  0.4926349 ],
       [-0.49972343,  1.58503996, -1.14632048,  0.37031588,  1.33078154,
         1.31313182, -0.16069932, -0.16541253, -0.43336985,  1.10821942],
       [ 0.46402083,  1.52258865,  0.47905126,  0.19134398,  1.45845499,
        -0.47314991,  0.13668149,  0.09587206,  0.26296573, -1.80309639]])

In [16]:
Ar[::,0:5]

array([[-0.5421967 ,  0.20519908,  0.25703849, -0.10050931, -1.21237108],
       [ 1.41186957,  0.94025984, -0.75769337,  2.36576275,  0.05619088],
       [ 0.70728982, -0.40604579, -1.45119135,  1.56556291, -1.54351312],
       [-0.60360182, -0.54863663,  0.59601694, -0.74212364,  0.82650736],
       [-0.45211338,  1.09802136,  1.44453281,  0.66108747, -0.17155868],
       [-1.58082051, -0.40375897, -1.78336633, -0.84720089,  0.39857613],
       [-1.01287266, -0.33034777, -0.40344416,  0.68774648,  0.45777982],
       [-0.49972343,  1.58503996, -1.14632048,  0.37031588,  1.33078154],
       [ 1.05454479, -1.68198386, -1.08086144, -1.51909282, -0.21482827],
       [ 0.46402083,  1.52258865,  0.47905126,  0.19134398,  1.45845499]])

In [18]:
Ar[1:-1,1:-1]=0

In [19]:
Ar

array([[-0.5421967 ,  0.20519908,  0.25703849, -0.10050931, -1.21237108,
        -1.61526741, -1.2717805 ,  0.06918799,  1.68844382,  2.02060615],
       [ 1.41186957,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        , -0.90122991],
       [ 0.70728982,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        , -1.11631523],
       [-0.60360182,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  1.041505  ],
       [-0.45211338,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  1.0188351 ],
       [-1.58082051,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.4926349 ],
       [-1.01287266,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        