In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,4,5,6,7,8,9])

In [4]:
x.mean()

5.0

In [5]:
x.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])

In [6]:
x.cumprod()

array([     1,      2,      6,     24,    120,    720,   5040,  40320,
       362880])

In [7]:
y = x>6

In [8]:
y

array([False, False, False, False, False, False,  True,  True,  True])

In [9]:
y.sum()

3

In [10]:
y.any()

True

In [12]:
y.all()

False

In [13]:
y.sort()

In [14]:
y

array([False, False, False, False, False, False,  True,  True,  True])

In [17]:
x = np.array([16,2,34,4,5,11,7,67,9])

In [18]:
x.sort()

In [19]:
x

array([ 2,  4,  5,  7,  9, 11, 16, 34, 67])

In [21]:
np.unique(x)

array([ 2,  4,  5,  7,  9, 11, 16, 34, 67])