In [3]:
import numpy as np

In [4]:
a = np.zeros((4,4))

In [5]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
b = np.ones((5,5))

In [8]:
b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
c = np.empty((8,8))

In [10]:
c

array([[0.00000000e+000, 4.68620793e-310, 2.30728657e-321,
                    nan, 4.68620793e-310, 0.00000000e+000,
        7.16535896e-090, 4.47593816e-091],
       [4.47593816e-091, 4.47593816e-091, 4.47593816e-091,
        4.47593816e-091, 4.47593816e-091, 4.47593816e-091,
        4.47593816e-091, 4.47593816e-091],
       [2.03794539e-178, 5.34712283e+160, 1.81975827e-176,
        6.01347002e-154, 6.01347002e-154, 6.01347002e-154,
        6.01347002e-154, 5.26742387e+170],
       [6.65370744e+217, 2.51516048e+180, 1.69592889e-152,
        7.49721430e+130, 3.13435284e+233, 7.28079528e+223,
        2.89570071e-057, 5.49628610e+170],
       [1.74160551e-152, 6.60925308e-062, 2.88067937e+214,
        3.06370797e-057, 7.49750087e+130, 4.47608802e-091,
        1.35292699e-023, 9.02133613e+217],
       [7.52132850e+130, 7.55273771e+130, 5.53177247e+228,
        1.44062231e-176, 7.53486016e-178, 6.60925309e-062,
        1.44062231e-176, 1.32189207e-177],
       [6.60925309e-062, 1.4406223

In [11]:
l = [1,2,3,4,5,6,7,8,9]

In [12]:
d = np.array(l)

In [13]:
d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
L = ["babar",1,1.2]
L

['babar', 1, 1.2]

In [19]:
e = np.array(L)
e

array(['babar', '1', '1.2'], dtype='<U5')

In [21]:
f = np.arange(1,100,10)
f

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [22]:
f.shape

(10,)

In [23]:
g = np.zeros((100))
g

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
h = g.reshape((2,2,5,5))
h

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [27]:
h.dtype

dtype('float64')

In [28]:
h.ndim

4