In [1]:
import numpy as np

In [2]:
X = np.array([10,16,3,7,8,9])

In [4]:
X

array([10, 16,  3,  7,  8,  9])

In [5]:
np.sqrt(X)

array([3.16227766, 4.        , 1.73205081, 2.64575131, 2.82842712,
       3.        ])

In [6]:
np.power(X,2)

array([100, 256,   9,  49,  64,  81])

In [8]:
y = np.array([12,6,8,9,13,17])

In [9]:
np.maximum(X,y)

array([12, 16,  8,  9, 13, 17])