In [2]:
import numpy as np
a = np.arange(1,13)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [3]:
b = a+2
b

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
a = np.arange(1,13).reshape((3,4))
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
print(a.dtype)

int64


In [6]:
a = np.arange(1,13).reshape((3,4)).astype('float64')
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [7]:
a = np.arange(1,13).astype('float64').reshape((3,4))
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [8]:
a = np.arange(1,13, dtype=np.float32).reshape((3,4))
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]], dtype=float32)

In [10]:
np.random.randn(3,3,3)*5

array([[[ -2.70481311,   3.92709306,   0.19630999],
        [  0.4309769 ,   1.21015708,   3.53105744],
        [  8.31680134,  -6.18243723, -14.08175583]],

       [[  3.94448692,  -4.5802323 ,  -0.95780897],
        [ -0.5970056 ,   4.33855321,   4.06205407],
        [ -5.50749581,   4.28926349,   7.46310548]],

       [[ -6.17196789,  -0.08259245,   1.01705545],
        [ -4.33273529,  -3.55596853,  -5.40638702],
        [ -4.02803894,  -7.710116  ,   4.24879219]]])

In [17]:
a = np.ones((3,3,3), dtype = np.int64)
a

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [20]:
a = np.zeros((3,3,3))
a

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [21]:
a = np.arange(1,28).reshape((3,3,3))
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [22]:
a.shape

(3, 3, 3)

In [23]:
a.shape= (9,3)
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

In [24]:
np.zeros_like(a)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [25]:
np.ones_like(a)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [26]:
np.ones_like(a) * 12

array([[12, 12, 12],
       [12, 12, 12],
       [12, 12, 12],
       [12, 12, 12],
       [12, 12, 12],
       [12, 12, 12],
       [12, 12, 12],
       [12, 12, 12],
       [12, 12, 12]])

In [27]:
np.ones_like(a) + 9

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [28]:
np.full_like(a, 10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [29]:
np.empty((3,3,3))

array([[[4.63750194e-310, 4.63750198e-310, 6.91791804e-310],
        [6.91791792e-310, 6.91791842e-310, 6.91791756e-310],
        [6.91791851e-310, 6.91791757e-310, 6.91791804e-310]],

       [[6.91791756e-310, 6.91791938e-310, 6.91791853e-310],
        [6.91791849e-310, 6.91791756e-310, 6.91791937e-310],
        [6.91791937e-310, 6.91791937e-310, 6.91791937e-310]],

       [[6.91791938e-310, 6.91791836e-310, 6.91791757e-310],
        [4.63750022e-310, 4.63750022e-310, 6.91791807e-310],
        [6.91791852e-310, 6.91791853e-310, 1.10670705e-321]]])

In [31]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [30]:
np.empty_like(a)

array([[ 93864084336128,  93864085123952, 140020219917512],
       [140020217474216, 140020227724488, 140020210310256],
       [140020229466240, 140020210507440, 140020220049480],
       [140020210310320, 140020247035952, 140020229912312],
       [140020229104168, 140020210310448, 140020246941856],
       [140020246851512, 140020246870448, 140020246945048],
       [140020247042352, 140020226491536, 140020210362600],
       [ 93864049458464,  93864049460256, 140020220587064],
       [140020229711776, 140020229806488,             224]])

In [32]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [34]:
np.identity(3,2)

TypeError: data type not understood

In [35]:
a = np.arange(1,13, dtype='int')
print(a.dtype)

int64


In [36]:
a = np.arange(1,13, dtype='i8')
print(a.dtype)

int64


In [37]:
np = a.astype(np.float64)
print(a.dtype)

int64


In [39]:
import numpy as np
a = np.arange(1,28, dtype='g').reshape((3,3,3))
print(a)
print(a.dtype)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]
  [ 7.  8.  9.]]

 [[10. 11. 12.]
  [13. 14. 15.]
  [16. 17. 18.]]

 [[19. 20. 21.]
  [22. 23. 24.]
  [25. 26. 27.]]]
float128


In [42]:
import numpy as np
np.full_like(a, 5, dtype=a.dtype)

array([[[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]]], dtype=float128)

In [43]:
a = np.arange(1,28).reshape((3,3,3))
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [47]:
b = [a % 3 == 0]
b

[array([[[False, False,  True],
         [False, False,  True],
         [False, False,  True]],
 
        [[False, False,  True],
         [False, False,  True],
         [False, False,  True]],
 
        [[False, False,  True],
         [False, False,  True],
         [False, False,  True]]])]

In [45]:
a[a % 3 == 0]

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])